#+TITLE: Implementation notes

* TODO-list

** TODO hardware-configuration.nix?
** TODO how to look up available packages?


#+begin_example
nix-env -f '<nixpkgs>' -iA emacs
#+end_example

- Are there any shorter commands?
- look up packages?
  - nix search wget
  - FIXME nix-env -qA emacs

** TODO stumpwm
1. the WM is installed using wm.stumpwm.enable = true, thus I must make my
   stumpwm package overwrite globally. This is defined in
   nixpkgs/nixos/modules/services/x11/window-managers/stumpwm.nix

2. there are two piece of definition.
   - nixpkgs/pkgs/development/lisp-modules/quicklisp-to-nix-output/stumpwm.nix,
     and this seems to be lispPackages.stumpwm?
   - nixpkgs/pkgs/applications/window-managers/stumpwm/default.nix, which should
     not be lispPackages.stumpwm, then what is it?

The lisp system support seems to be pretty bad. I probably just stick with guix
and work out the non-free staff and linux kernel.

Currently, I cannot build all lispPackages.XXX, with the error

#+begin_example
/nix/store/whpnlfj79vd8p175rp1bwg0x7wz5lmj1-stdenv-linux/setup: line 320: [@]: bad substitution
#+end_example

I ran the following command in local nixpkgs root:
#+begin_example
nix-build -A lispPackages.cl-ppcre
#+end_example

** TODO multiple DE
** TODO nvidia driver
** TODO sway
The border feature.
** DPI
** libinput natural scroll

* Wiki draft

=man configuration.nix= shows all options offline.

** channel
list current channel:

#+begin_example
sudo nix-channel --list
# >>> nixos https://nixos.org/channels/nixos-19.09
#+end_example

Add the unstable channel:

#+begin_example
sudo nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
#+end_example

Do a full upgrade:

#+begin_example
sudo nixos-rebuild switch --upgrade
#+end_example

Note that the channel setting is per-user, so for system upgrade, you need to set the root's channel.


* References
- https://github.com/michaelpj/nixos-config
- https://github.com/Tmplt/nixos-config
- https://github.com/benley/dotfiles
- https://github.com/NixOS/nix-mode
