#+TITLE: My NixOS configuration

To use, clone this to +any path+ =/home/hebi/git/nixos/configuration.nix=, and

#+begin_example
sudo nixos-rebuild switch -I nix-config=./configuration.nix
#+end_example

All subsequent build will honor that path, i.e.

#+begin_example
sudo nixos-rebuild switch
#+end_example

To roll back to previous generation:

#+begin_example
sudo nixos-rebuild switch --rollback
#+end_example


* StumpWM

StumpWM is best used with clx-truetype, otherwise it is super awkward to adjust
fonts. But it is not very straight-forward, because NixOS does not use quicklisp
to manage common lisp libraries, but uses =/nix/store/...= and hard code those
paths into =NIX_LISP_ASDF_PATHS=. To support stumpwm, you cannot use the
=stumpwm= executable. Instead, you need:

1. use a wrapper package, =stumpwm-wrapper=, for starting StumpWM. It basically
   adds =clx-truetype= and =swank= into =NIX_LISP_ASDF_PATHS=, and start stumpwm
   via sbcl
2. use a wrapper of stumpwm window manager, which register a xsession with the
   =stumpwm-wrapper= script as starting command

As an exmaple, your configuration.nix would look like this:

#+BEGIN_SRC nix
{
  imports =
    [ ./hardware-configuration.nix
      ./nixos/window-manager.nix ];
  services.xserver.windowManager.stumpwm-wrapper.enable = true;
}
#+END_SRC

Also, on NixOS, the clx-truetype is compiled by Nix bulid user, which cause
=xft:+font-cache-filename+= to be set to =/build/.fonts=, and that is not
accessible. Thus, in your stumpwm config, you need to go into =:xft= package and
set it to =$HOME/.fonts=, something like:


#+BEGIN_SRC lisp
(in-package :xft)
(defparameter +font-cache-filename+
  #.(merge-pathnames "font-cache.sexp"
                     (merge-pathnames ".fonts/" (user-homedir-pathname))))
;; switch back to :stumpwm (not :cl-user!)
(in-package :stumpwm)

(if (not (find "Source Code Pro" (xft:get-font-families)
               :test #'equal))
    ;; cache fonts. pretty slow
    (xft:cache-fonts))

;; (xft:get-font-families) should work now

(set-font
 (list
  (make-instance 'xft:font
                 :family "WenQuanYi Micro Hei Mono"
                 :subfamily "Regular" :size 12)
  (make-instance 'xft:font
                 :family "Source Code Pro"
                 :subfamily "Regular" :size 12)))
#+END_SRC

